#!/usr/bin/python
# -*- encoding: utf-8 -*-

import os
import os.path as osp
import json

import torch
from torch.utils.data import Dataset, DataLoader
import torch.distributed as dist
import cv2
import numpy as np

import lib.transform_cv2 as T
from lib.sampler import RepeatedDistSampler
from lib.base_dataset import BaseDataset, TransformationTrain, TransformationVal


labels_info = [{'color': [0, 0, 0],
  'id': 0,
  'ignoreInEval': False,
  'name': 'unlabeled',
  'trainId': 255},
 {'color': [255, 255, 255],
  'id': 1,
  'ignoreInEval': False,
  'name': 'person',
  'trainId': 0},
 {'color': [148, 27, 102],
  'id': 2,
  'ignoreInEval': False,
  'name': 'bicycle',
  'trainId': 1},
 {'color': [149, 28, 103],
  'id': 3,
  'ignoreInEval': False,
  'name': 'car',
  'trainId': 2},
 {'color': [150, 29, 104],
  'id': 4,
  'ignoreInEval': False,
  'name': 'motorcycle',
  'trainId': 3},
 {'color': [0, 0, 0],
  'id': 5,
  'ignoreInEval': False,
  'name': 'airplane',
  'trainId': 255},
 {'color': [152, 31, 106],
  'id': 6,
  'ignoreInEval': False,
  'name': 'bus',
  'trainId': 4},
 {'color': [0, 0, 0],
  'id': 7,
  'ignoreInEval': False,
  'name': 'train',
  'trainId': 255},
 {'color': [154, 33, 108],
  'id': 8,
  'ignoreInEval': False,
  'name': 'truck',
  'trainId': 5},
 {'color': [0, 0, 0],
  'id': 9,
  'ignoreInEval': False,
  'name': 'boat',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 10,
  'ignoreInEval': False,
  'name': 'traffic',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 11,
  'ignoreInEval': False,
  'name': 'fire',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 12,
  'ignoreInEval': False,
  'name': 'street',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 13,
  'ignoreInEval': False,
  'name': 'stop',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 14,
  'ignoreInEval': False,
  'name': 'parking',
  'trainId': 255},
 {'color': [161, 40, 115],
  'id': 15,
  'ignoreInEval': False,
  'name': 'bench',
  'trainId': 6},
 {'color': [162, 41, 116],
  'id': 16,
  'ignoreInEval': False,
  'name': 'bird',
  'trainId': 7},
 {'color': [163, 42, 117],
  'id': 17,
  'ignoreInEval': False,
  'name': 'cat',
  'trainId': 8},
 {'color': [164, 43, 118],
  'id': 18,
  'ignoreInEval': False,
  'name': 'dog',
  'trainId': 9},
 {'color': [0, 0, 0],
  'id': 19,
  'ignoreInEval': False,
  'name': 'horse',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 20,
  'ignoreInEval': False,
  'name': 'sheep',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 21,
  'ignoreInEval': False,
  'name': 'cow',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 22,
  'ignoreInEval': False,
  'name': 'elephant',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 23,
  'ignoreInEval': False,
  'name': 'bear',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 24,
  'ignoreInEval': False,
  'name': 'zebra',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 25,
  'ignoreInEval': False,
  'name': 'giraffe',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 26,
  'ignoreInEval': False,
  'name': 'hat',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 27,
  'ignoreInEval': False,
  'name': 'backpack',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 28,
  'ignoreInEval': False,
  'name': 'umbrella',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 29,
  'ignoreInEval': False,
  'name': 'shoe',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 30,
  'ignoreInEval': False,
  'name': 'eye',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 31,
  'ignoreInEval': False,
  'name': 'handbag',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 32,
  'ignoreInEval': False,
  'name': 'tie',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 33,
  'ignoreInEval': False,
  'name': 'suitcase',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 34,
  'ignoreInEval': False,
  'name': 'frisbee',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 35,
  'ignoreInEval': False,
  'name': 'skis',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 36,
  'ignoreInEval': False,
  'name': 'snowboard',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 37,
  'ignoreInEval': False,
  'name': 'sports',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 38,
  'ignoreInEval': False,
  'name': 'kite',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 39,
  'ignoreInEval': False,
  'name': 'baseball',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 40,
  'ignoreInEval': False,
  'name': 'baseball',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 41,
  'ignoreInEval': False,
  'name': 'skateboard',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 42,
  'ignoreInEval': False,
  'name': 'surfboard',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 43,
  'ignoreInEval': False,
  'name': 'tennis',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 44,
  'ignoreInEval': False,
  'name': 'bottle',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 45,
  'ignoreInEval': False,
  'name': 'plate',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 46,
  'ignoreInEval': False,
  'name': 'wine',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 47,
  'ignoreInEval': False,
  'name': 'cup',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 48,
  'ignoreInEval': False,
  'name': 'fork',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 49,
  'ignoreInEval': False,
  'name': 'knife',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 50,
  'ignoreInEval': False,
  'name': 'spoon',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 51,
  'ignoreInEval': False,
  'name': 'bowl',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 52,
  'ignoreInEval': False,
  'name': 'banana',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 53,
  'ignoreInEval': False,
  'name': 'apple',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 54,
  'ignoreInEval': False,
  'name': 'sandwich',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 55,
  'ignoreInEval': False,
  'name': 'orange',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 56,
  'ignoreInEval': False,
  'name': 'broccoli',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 57,
  'ignoreInEval': False,
  'name': 'carrot',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 58,
  'ignoreInEval': False,
  'name': 'hot',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 59,
  'ignoreInEval': False,
  'name': 'pizza',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 60,
  'ignoreInEval': False,
  'name': 'donut',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 61,
  'ignoreInEval': False,
  'name': 'cake',
  'trainId': 255},
 {'color': [208, 87, 162],
  'id': 62,
  'ignoreInEval': False,
  'name': 'chair',
  'trainId': 10},
 {'color': [0, 0, 0],
  'id': 63,
  'ignoreInEval': False,
  'name': 'couch',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 64,
  'ignoreInEval': False,
  'name': 'potted',
  'trainId': 255},
 {'color': [211, 90, 165],
  'id': 65,
  'ignoreInEval': False,
  'name': 'bed',
  'trainId': 11},
 {'color': [0, 0, 0],
  'id': 66,
  'ignoreInEval': False,
  'name': 'mirror',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 67,
  'ignoreInEval': False,
  'name': 'dining',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 68,
  'ignoreInEval': False,
  'name': 'window',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 69,
  'ignoreInEval': False,
  'name': 'desk',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 70,
  'ignoreInEval': False,
  'name': 'toilet',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 71,
  'ignoreInEval': False,
  'name': 'door',
  'trainId': 255},
 {'color': [218, 97, 172],
  'id': 72,
  'ignoreInEval': False,
  'name': 'tv',
  'trainId': 12},
 {'color': [219, 98, 173],
  'id': 73,
  'ignoreInEval': False,
  'name': 'laptop',
  'trainId': 13},
 {'color': [0, 0, 0],
  'id': 74,
  'ignoreInEval': False,
  'name': 'mouse',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 75,
  'ignoreInEval': False,
  'name': 'remote',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 76,
  'ignoreInEval': False,
  'name': 'keyboard',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 77,
  'ignoreInEval': False,
  'name': 'cell',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 78,
  'ignoreInEval': False,
  'name': 'microwave',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 79,
  'ignoreInEval': False,
  'name': 'oven',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 80,
  'ignoreInEval': False,
  'name': 'toaster',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 81,
  'ignoreInEval': False,
  'name': 'sink',
  'trainId': 255},
 {'color': [228, 107, 182],
  'id': 82,
  'ignoreInEval': False,
  'name': 'refrigerator',
  'trainId': 14},
 {'color': [0, 0, 0],
  'id': 83,
  'ignoreInEval': False,
  'name': 'blender',
  'trainId': 255},
 {'color': [230, 109, 184],
  'id': 84,
  'ignoreInEval': False,
  'name': 'book',
  'trainId': 15},
 {'color': [231, 110, 185],
  'id': 85,
  'ignoreInEval': False,
  'name': 'clock',
  'trainId': 16},
 {'color': [0, 0, 0],
  'id': 86,
  'ignoreInEval': False,
  'name': 'vase',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 87,
  'ignoreInEval': False,
  'name': 'scissors',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 88,
  'ignoreInEval': False,
  'name': 'teddy',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 89,
  'ignoreInEval': False,
  'name': 'hair',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 90,
  'ignoreInEval': False,
  'name': 'toothbrush',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 91,
  'ignoreInEval': False,
  'name': 'hair',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 92,
  'ignoreInEval': False,
  'name': 'banner',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 93,
  'ignoreInEval': False,
  'name': 'blanket',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 94,
  'ignoreInEval': False,
  'name': 'branch',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 95,
  'ignoreInEval': False,
  'name': 'bridge',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 96,
  'ignoreInEval': False,
  'name': 'building',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 97,
  'ignoreInEval': False,
  'name': 'bush',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 98,
  'ignoreInEval': False,
  'name': 'cabinet',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 99,
  'ignoreInEval': False,
  'name': 'cage',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 100,
  'ignoreInEval': False,
  'name': 'cardboard',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 101,
  'ignoreInEval': False,
  'name': 'carpet',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 102,
  'ignoreInEval': False,
  'name': 'ceiling',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 103,
  'ignoreInEval': False,
  'name': 'ceiling',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 104,
  'ignoreInEval': False,
  'name': 'cloth',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 105,
  'ignoreInEval': False,
  'name': 'clothes',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 106,
  'ignoreInEval': False,
  'name': 'clouds',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 107,
  'ignoreInEval': False,
  'name': 'counter',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 108,
  'ignoreInEval': False,
  'name': 'cupboard',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 109,
  'ignoreInEval': False,
  'name': 'curtain',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 110,
  'ignoreInEval': False,
  'name': 'desk',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 111,
  'ignoreInEval': False,
  'name': 'dirt',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 112,
  'ignoreInEval': False,
  'name': 'door',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 113,
  'ignoreInEval': False,
  'name': 'fence',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 114,
  'ignoreInEval': False,
  'name': 'floor',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 115,
  'ignoreInEval': False,
  'name': 'floor',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 116,
  'ignoreInEval': False,
  'name': 'floor',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 117,
  'ignoreInEval': False,
  'name': 'floor',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 118,
  'ignoreInEval': False,
  'name': 'floor',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 119,
  'ignoreInEval': False,
  'name': 'flower',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 120,
  'ignoreInEval': False,
  'name': 'fog',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 121,
  'ignoreInEval': False,
  'name': 'food',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 122,
  'ignoreInEval': False,
  'name': 'fruit',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 123,
  'ignoreInEval': False,
  'name': 'furniture',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 124,
  'ignoreInEval': False,
  'name': 'grass',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 125,
  'ignoreInEval': False,
  'name': 'gravel',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 126,
  'ignoreInEval': False,
  'name': 'ground',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 127,
  'ignoreInEval': False,
  'name': 'hill',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 128,
  'ignoreInEval': False,
  'name': 'house',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 129,
  'ignoreInEval': False,
  'name': 'leaves',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 130,
  'ignoreInEval': False,
  'name': 'light',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 131,
  'ignoreInEval': False,
  'name': 'mat',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 132,
  'ignoreInEval': False,
  'name': 'metal',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 133,
  'ignoreInEval': False,
  'name': 'mirror',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 134,
  'ignoreInEval': False,
  'name': 'moss',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 135,
  'ignoreInEval': False,
  'name': 'mountain',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 136,
  'ignoreInEval': False,
  'name': 'mud',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 137,
  'ignoreInEval': False,
  'name': 'napkin',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 138,
  'ignoreInEval': False,
  'name': 'net',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 139,
  'ignoreInEval': False,
  'name': 'paper',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 140,
  'ignoreInEval': False,
  'name': 'pavement',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 141,
  'ignoreInEval': False,
  'name': 'pillow',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 142,
  'ignoreInEval': False,
  'name': 'plant',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 143,
  'ignoreInEval': False,
  'name': 'plastic',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 144,
  'ignoreInEval': False,
  'name': 'platform',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 145,
  'ignoreInEval': False,
  'name': 'playingfield',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 146,
  'ignoreInEval': False,
  'name': 'railing',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 147,
  'ignoreInEval': False,
  'name': 'railroad',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 148,
  'ignoreInEval': False,
  'name': 'river',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 149,
  'ignoreInEval': False,
  'name': 'road',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 150,
  'ignoreInEval': False,
  'name': 'rock',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 151,
  'ignoreInEval': False,
  'name': 'roof',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 152,
  'ignoreInEval': False,
  'name': 'rug',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 153,
  'ignoreInEval': False,
  'name': 'salad',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 154,
  'ignoreInEval': False,
  'name': 'sand',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 155,
  'ignoreInEval': False,
  'name': 'sea',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 156,
  'ignoreInEval': False,
  'name': 'shelf',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 157,
  'ignoreInEval': False,
  'name': 'sky',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 158,
  'ignoreInEval': False,
  'name': 'skyscraper',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 159,
  'ignoreInEval': False,
  'name': 'snow',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 160,
  'ignoreInEval': False,
  'name': 'solid',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 161,
  'ignoreInEval': False,
  'name': 'stairs',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 162,
  'ignoreInEval': False,
  'name': 'stone',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 163,
  'ignoreInEval': False,
  'name': 'straw',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 164,
  'ignoreInEval': False,
  'name': 'structural',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 165,
  'ignoreInEval': False,
  'name': 'table',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 166,
  'ignoreInEval': False,
  'name': 'tent',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 167,
  'ignoreInEval': False,
  'name': 'textile',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 168,
  'ignoreInEval': False,
  'name': 'towel',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 169,
  'ignoreInEval': False,
  'name': 'tree',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 170,
  'ignoreInEval': False,
  'name': 'vegetable',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 171,
  'ignoreInEval': False,
  'name': 'wall',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 172,
  'ignoreInEval': False,
  'name': 'wall',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 173,
  'ignoreInEval': False,
  'name': 'wall',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 174,
  'ignoreInEval': False,
  'name': 'wall',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 175,
  'ignoreInEval': False,
  'name': 'wall',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 176,
  'ignoreInEval': False,
  'name': 'wall',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 177,
  'ignoreInEval': False,
  'name': 'wall',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 178,
  'ignoreInEval': False,
  'name': 'water',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 179,
  'ignoreInEval': False,
  'name': 'waterdrops',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 180,
  'ignoreInEval': False,
  'name': 'window',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 181,
  'ignoreInEval': False,
  'name': 'window',
  'trainId': 255},
 {'color': [0, 0, 0],
  'id': 182,
  'ignoreInEval': False,
  'name': 'wood',
  'trainId': 255}]




class Coco(BaseDataset):
    '''
    '''
    def __init__(self, dataroot, annpath, trans_func=None, mode='train'):
        super(Coco, self).__init__(
                dataroot, annpath, trans_func, mode)
        self.n_cats = 19
        self.lb_ignore = 255
        self.lb_map = np.arange(256).astype(np.uint8)
        for el in labels_info:
            self.lb_map[el['id']] = el['trainId']

        self.to_tensor = T.ToTensor(
            mean=(0.3257, 0.3690, 0.3223), # city, rgb
            std=(0.2112, 0.2148, 0.2115),
        )


def get_data_loader(datapth, annpath, ims_per_gpu, scales, cropsize, max_iter=None, mode='train', distributed=True):
    if mode == 'train':
        trans_func = TransformationTrain(scales, cropsize)
        batchsize = ims_per_gpu
        shuffle = True
        drop_last = True
    elif mode == 'val':
        trans_func = TransformationVal(cropsize)
        batchsize = ims_per_gpu
        shuffle = False
        drop_last = False

    ds = Coco(datapth, annpath, trans_func=trans_func, mode=mode)

    if distributed:
        assert dist.is_available(), "dist should be initialzed"
        if mode == 'train':
            assert not max_iter is None
            n_train_imgs = ims_per_gpu * dist.get_world_size() * max_iter
            sampler = RepeatedDistSampler(ds, n_train_imgs, shuffle=shuffle)
        else:
            sampler = torch.utils.data.distributed.DistributedSampler(
                ds, shuffle=shuffle)
        batchsampler = torch.utils.data.sampler.BatchSampler(
            sampler, batchsize, drop_last=drop_last
        )
        dl = DataLoader(
            ds,
            batch_sampler=batchsampler,
            num_workers=4,
            pin_memory=True,
        )
    else:
        dl = DataLoader(
            ds,
            batch_size=batchsize,
            shuffle=shuffle,
            drop_last=drop_last,
            num_workers=4,
            pin_memory=True,
        )
    return dl



if __name__ == "__main__":
    from tqdm import tqdm
    from torch.utils.data import DataLoader
    ds = Coco('./data/', mode='val')
    dl = DataLoader(ds,
                    batch_size = 4,
                    shuffle = True,
                    num_workers = 4,
                    drop_last = True)
    for imgs, label in dl:
        print(len(imgs))
        for el in imgs:
            print(el.size())
        break
