#!/usr/bin/python
# -*- encoding: utf-8 -*-

import os
import os.path as osp
import json

import torch
from torch.utils.data import Dataset, DataLoader
import torch.distributed as dist
import cv2
import numpy as np

import lib.transform_cv2 as T
from lib.sampler import RepeatedDistSampler
from lib.base_dataset import BaseDataset, TransformationTrain, TransformationVal


labels_info = [{'category': 'person',
  'catid': 0,
  'color': (6, 147, 15),
  'hasInstances': True,
  'id': 1,
  'ignoreInEval': False,
  'name': 'person',
  'trainId': 0},
 {'category': 'vehicle',
  'catid': 0,
  'color': (9, 150, 18),
  'hasInstances': True,
  'id': 2,
  'ignoreInEval': False,
  'name': 'bicycle',
  'trainId': 1},
 {'category': 'vehicle',
  'catid': 0,
  'color': (12, 153, 21),
  'hasInstances': True,
  'id': 3,
  'ignoreInEval': False,
  'name': 'car',
  'trainId': 2},
 {'category': 'vehicle',
  'catid': 0,
  'color': (15, 156, 24),
  'hasInstances': True,
  'id': 4,
  'ignoreInEval': False,
  'name': 'motorcycle',
  'trainId': 3},
 {'category': 'vehicle',
  'catid': 0,
  'color': (18, 159, 27),
  'hasInstances': True,
  'id': 5,
  'ignoreInEval': False,
  'name': 'airplane',
  'trainId': 255},
 {'category': 'vehicle',
  'catid': 0,
  'color': (21, 162, 30),
  'hasInstances': True,
  'id': 6,
  'ignoreInEval': False,
  'name': 'bus',
  'trainId': 4},
 {'category': 'vehicle',
  'catid': 0,
  'color': (24, 165, 33),
  'hasInstances': True,
  'id': 7,
  'ignoreInEval': False,
  'name': 'train',
  'trainId': 255},
 {'category': 'vehicle',
  'catid': 0,
  'color': (27, 168, 36),
  'hasInstances': True,
  'id': 8,
  'ignoreInEval': False,
  'name': 'truck',
  'trainId': 5},
 {'category': 'vehicle',
  'catid': 0,
  'color': (30, 171, 39),
  'hasInstances': True,
  'id': 9,
  'ignoreInEval': False,
  'name': 'boat',
  'trainId': 255},
 {'category': 'outdoor',
  'catid': 0,
  'color': (33, 174, 42),
  'hasInstances': True,
  'id': 10,
  'ignoreInEval': False,
  'name': 'traffic light',
  'trainId': 255},
 {'category': 'outdoor',
  'catid': 0,
  'color': (36, 177, 45),
  'hasInstances': True,
  'id': 11,
  'ignoreInEval': False,
  'name': 'fire hydrant',
  'trainId': 255},
 {'category': 'outdoor',
  'catid': 0,
  'color': (39, 180, 48),
  'hasInstances': True,
  'id': 13,
  'ignoreInEval': False,
  'name': 'stop sign',
  'trainId': 255},
 {'category': 'outdoor',
  'catid': 0,
  'color': (42, 183, 51),
  'hasInstances': True,
  'id': 14,
  'ignoreInEval': False,
  'name': 'parking meter',
  'trainId': 255},
 {'category': 'outdoor',
  'catid': 0,
  'color': (45, 186, 54),
  'hasInstances': True,
  'id': 15,
  'ignoreInEval': False,
  'name': 'bench',
  'trainId': 6},
 {'category': 'animal',
  'catid': 0,
  'color': (48, 189, 57),
  'hasInstances': True,
  'id': 16,
  'ignoreInEval': False,
  'name': 'bird',
  'trainId': 7},
 {'category': 'animal',
  'catid': 0,
  'color': (51, 192, 60),
  'hasInstances': True,
  'id': 17,
  'ignoreInEval': False,
  'name': 'cat',
  'trainId': 8},
 {'category': 'animal',
  'catid': 0,
  'color': (54, 195, 63),
  'hasInstances': True,
  'id': 18,
  'ignoreInEval': False,
  'name': 'dog',
  'trainId': 9},
 {'category': 'animal',
  'catid': 0,
  'color': (57, 198, 66),
  'hasInstances': True,
  'id': 19,
  'ignoreInEval': False,
  'name': 'horse',
  'trainId': 255},
 {'category': 'animal',
  'catid': 0,
  'color': (60, 201, 69),
  'hasInstances': True,
  'id': 20,
  'ignoreInEval': False,
  'name': 'sheep',
  'trainId': 255},
 {'category': 'animal',
  'catid': 0,
  'color': (63, 204, 72),
  'hasInstances': True,
  'id': 21,
  'ignoreInEval': False,
  'name': 'cow',
  'trainId': 255},
 {'category': 'animal',
  'catid': 0,
  'color': (66, 207, 75),
  'hasInstances': True,
  'id': 22,
  'ignoreInEval': False,
  'name': 'elephant',
  'trainId': 255},
 {'category': 'animal',
  'catid': 0,
  'color': (69, 210, 78),
  'hasInstances': True,
  'id': 23,
  'ignoreInEval': False,
  'name': 'bear',
  'trainId': 255},
 {'category': 'animal',
  'catid': 0,
  'color': (72, 213, 81),
  'hasInstances': True,
  'id': 24,
  'ignoreInEval': False,
  'name': 'zebra',
  'trainId': 255},
 {'category': 'animal',
  'catid': 0,
  'color': (75, 216, 84),
  'hasInstances': True,
  'id': 25,
  'ignoreInEval': False,
  'name': 'giraffe',
  'trainId': 255},
 {'category': 'accessory',
  'catid': 0,
  'color': (78, 219, 87),
  'hasInstances': True,
  'id': 27,
  'ignoreInEval': False,
  'name': 'backpack',
  'trainId': 255},
 {'category': 'accessory',
  'catid': 0,
  'color': (81, 222, 90),
  'hasInstances': True,
  'id': 28,
  'ignoreInEval': False,
  'name': 'umbrella',
  'trainId': 255},
 {'category': 'accessory',
  'catid': 0,
  'color': (84, 225, 93),
  'hasInstances': True,
  'id': 31,
  'ignoreInEval': False,
  'name': 'handbag',
  'trainId': 255},
 {'category': 'accessory',
  'catid': 0,
  'color': (87, 228, 96),
  'hasInstances': True,
  'id': 32,
  'ignoreInEval': False,
  'name': 'tie',
  'trainId': 255},
 {'category': 'accessory',
  'catid': 0,
  'color': (90, 231, 99),
  'hasInstances': True,
  'id': 33,
  'ignoreInEval': False,
  'name': 'suitcase',
  'trainId': 255},
 {'category': 'sports',
  'catid': 0,
  'color': (93, 234, 102),
  'hasInstances': True,
  'id': 34,
  'ignoreInEval': False,
  'name': 'frisbee',
  'trainId': 255},
 {'category': 'sports',
  'catid': 0,
  'color': (96, 237, 105),
  'hasInstances': True,
  'id': 35,
  'ignoreInEval': False,
  'name': 'skis',
  'trainId': 255},
 {'category': 'sports',
  'catid': 0,
  'color': (99, 240, 108),
  'hasInstances': True,
  'id': 36,
  'ignoreInEval': False,
  'name': 'snowboard',
  'trainId': 255},
 {'category': 'sports',
  'catid': 0,
  'color': (102, 243, 111),
  'hasInstances': True,
  'id': 37,
  'ignoreInEval': False,
  'name': 'sports ball',
  'trainId': 255},
 {'category': 'sports',
  'catid': 0,
  'color': (105, 246, 114),
  'hasInstances': True,
  'id': 38,
  'ignoreInEval': False,
  'name': 'kite',
  'trainId': 255},
 {'category': 'sports',
  'catid': 0,
  'color': (108, 249, 117),
  'hasInstances': True,
  'id': 39,
  'ignoreInEval': False,
  'name': 'baseball bat',
  'trainId': 255},
 {'category': 'sports',
  'catid': 0,
  'color': (111, 252, 120),
  'hasInstances': True,
  'id': 40,
  'ignoreInEval': False,
  'name': 'baseball glove',
  'trainId': 255},
 {'category': 'sports',
  'catid': 0,
  'color': (114, 255, 123),
  'hasInstances': True,
  'id': 41,
  'ignoreInEval': False,
  'name': 'skateboard',
  'trainId': 255},
 {'category': 'sports',
  'catid': 0,
  'color': (117, 2, 126),
  'hasInstances': True,
  'id': 42,
  'ignoreInEval': False,
  'name': 'surfboard',
  'trainId': 255},
 {'category': 'sports',
  'catid': 0,
  'color': (120, 5, 129),
  'hasInstances': True,
  'id': 43,
  'ignoreInEval': False,
  'name': 'tennis racket',
  'trainId': 255},
 {'category': 'kitchen',
  'catid': 0,
  'color': (123, 8, 132),
  'hasInstances': True,
  'id': 44,
  'ignoreInEval': False,
  'name': 'bottle',
  'trainId': 255},
 {'category': 'kitchen',
  'catid': 0,
  'color': (126, 11, 135),
  'hasInstances': True,
  'id': 46,
  'ignoreInEval': False,
  'name': 'wine glass',
  'trainId': 255},
 {'category': 'kitchen',
  'catid': 0,
  'color': (129, 14, 138),
  'hasInstances': True,
  'id': 47,
  'ignoreInEval': False,
  'name': 'cup',
  'trainId': 255},
 {'category': 'kitchen',
  'catid': 0,
  'color': (132, 17, 141),
  'hasInstances': True,
  'id': 48,
  'ignoreInEval': False,
  'name': 'fork',
  'trainId': 255},
 {'category': 'kitchen',
  'catid': 0,
  'color': (135, 20, 144),
  'hasInstances': True,
  'id': 49,
  'ignoreInEval': False,
  'name': 'knife',
  'trainId': 255},
 {'category': 'kitchen',
  'catid': 0,
  'color': (138, 23, 147),
  'hasInstances': True,
  'id': 50,
  'ignoreInEval': False,
  'name': 'spoon',
  'trainId': 255},
 {'category': 'kitchen',
  'catid': 0,
  'color': (141, 26, 150),
  'hasInstances': True,
  'id': 51,
  'ignoreInEval': False,
  'name': 'bowl',
  'trainId': 255},
 {'category': 'food',
  'catid': 0,
  'color': (144, 29, 153),
  'hasInstances': True,
  'id': 52,
  'ignoreInEval': False,
  'name': 'banana',
  'trainId': 255},
 {'category': 'food',
  'catid': 0,
  'color': (147, 32, 156),
  'hasInstances': True,
  'id': 53,
  'ignoreInEval': False,
  'name': 'apple',
  'trainId': 255},
 {'category': 'food',
  'catid': 0,
  'color': (150, 35, 159),
  'hasInstances': True,
  'id': 54,
  'ignoreInEval': False,
  'name': 'sandwich',
  'trainId': 255},
 {'category': 'food',
  'catid': 0,
  'color': (153, 38, 162),
  'hasInstances': True,
  'id': 55,
  'ignoreInEval': False,
  'name': 'orange',
  'trainId': 255},
 {'category': 'food',
  'catid': 0,
  'color': (156, 41, 165),
  'hasInstances': True,
  'id': 56,
  'ignoreInEval': False,
  'name': 'broccoli',
  'trainId': 255},
 {'category': 'food',
  'catid': 0,
  'color': (159, 44, 168),
  'hasInstances': True,
  'id': 57,
  'ignoreInEval': False,
  'name': 'carrot',
  'trainId': 255},
 {'category': 'food',
  'catid': 0,
  'color': (162, 47, 171),
  'hasInstances': True,
  'id': 58,
  'ignoreInEval': False,
  'name': 'hot dog',
  'trainId': 255},
 {'category': 'food',
  'catid': 0,
  'color': (165, 50, 174),
  'hasInstances': True,
  'id': 59,
  'ignoreInEval': False,
  'name': 'pizza',
  'trainId': 255},
 {'category': 'food',
  'catid': 0,
  'color': (168, 53, 177),
  'hasInstances': True,
  'id': 60,
  'ignoreInEval': False,
  'name': 'donut',
  'trainId': 255},
 {'category': 'food',
  'catid': 0,
  'color': (171, 56, 180),
  'hasInstances': True,
  'id': 61,
  'ignoreInEval': False,
  'name': 'cake',
  'trainId': 255},
 {'category': 'furniture',
  'catid': 0,
  'color': (174, 59, 183),
  'hasInstances': True,
  'id': 62,
  'ignoreInEval': False,
  'name': 'chair',
  'trainId': 10},
 {'category': 'furniture',
  'catid': 0,
  'color': (177, 62, 186),
  'hasInstances': True,
  'id': 63,
  'ignoreInEval': False,
  'name': 'couch',
  'trainId': 255},
 {'category': 'furniture',
  'catid': 0,
  'color': (180, 65, 189),
  'hasInstances': True,
  'id': 64,
  'ignoreInEval': False,
  'name': 'potted plant',
  'trainId': 255},
 {'category': 'furniture',
  'catid': 0,
  'color': (183, 68, 192),
  'hasInstances': True,
  'id': 65,
  'ignoreInEval': False,
  'name': 'bed',
  'trainId': 11},
 {'category': 'furniture',
  'catid': 0,
  'color': (186, 71, 195),
  'hasInstances': True,
  'id': 67,
  'ignoreInEval': False,
  'name': 'dining table',
  'trainId': 12},
 {'category': 'furniture',
  'catid': 0,
  'color': (189, 74, 198),
  'hasInstances': True,
  'id': 70,
  'ignoreInEval': False,
  'name': 'toilet',
  'trainId': 255},
 {'category': 'electronic',
  'catid': 0,
  'color': (192, 77, 201),
  'hasInstances': True,
  'id': 72,
  'ignoreInEval': False,
  'name': 'tv',
  'trainId': 13},
 {'category': 'electronic',
  'catid': 0,
  'color': (195, 80, 204),
  'hasInstances': True,
  'id': 73,
  'ignoreInEval': False,
  'name': 'laptop',
  'trainId': 14},
 {'category': 'electronic',
  'catid': 0,
  'color': (198, 83, 207),
  'hasInstances': True,
  'id': 74,
  'ignoreInEval': False,
  'name': 'mouse',
  'trainId': 255},
 {'category': 'electronic',
  'catid': 0,
  'color': (201, 86, 210),
  'hasInstances': True,
  'id': 75,
  'ignoreInEval': False,
  'name': 'remote',
  'trainId': 255},
 {'category': 'electronic',
  'catid': 0,
  'color': (204, 89, 213),
  'hasInstances': True,
  'id': 76,
  'ignoreInEval': False,
  'name': 'keyboard',
  'trainId': 255},
 {'category': 'electronic',
  'catid': 0,
  'color': (207, 92, 216),
  'hasInstances': True,
  'id': 77,
  'ignoreInEval': False,
  'name': 'cell phone',
  'trainId': 15},
 {'category': 'appliance',
  'catid': 0,
  'color': (210, 95, 219),
  'hasInstances': True,
  'id': 78,
  'ignoreInEval': False,
  'name': 'microwave',
  'trainId': 255},
 {'category': 'appliance',
  'catid': 0,
  'color': (213, 98, 222),
  'hasInstances': True,
  'id': 79,
  'ignoreInEval': False,
  'name': 'oven',
  'trainId': 255},
 {'category': 'appliance',
  'catid': 0,
  'color': (216, 101, 225),
  'hasInstances': True,
  'id': 80,
  'ignoreInEval': False,
  'name': 'toaster',
  'trainId': 255},
 {'category': 'appliance',
  'catid': 0,
  'color': (219, 104, 228),
  'hasInstances': True,
  'id': 81,
  'ignoreInEval': False,
  'name': 'sink',
  'trainId': 255},
 {'category': 'appliance',
  'catid': 0,
  'color': (222, 107, 231),
  'hasInstances': True,
  'id': 82,
  'ignoreInEval': False,
  'name': 'refrigerator',
  'trainId': 16},
 {'category': 'indoor',
  'catid': 0,
  'color': (225, 110, 234),
  'hasInstances': True,
  'id': 84,
  'ignoreInEval': False,
  'name': 'book',
  'trainId': 17},
 {'category': 'indoor',
  'catid': 0,
  'color': (228, 113, 237),
  'hasInstances': True,
  'id': 85,
  'ignoreInEval': False,
  'name': 'clock',
  'trainId': 18},
 {'category': 'indoor',
  'catid': 0,
  'color': (231, 116, 240),
  'hasInstances': True,
  'id': 86,
  'ignoreInEval': False,
  'name': 'vase',
  'trainId': 255},
 {'category': 'indoor',
  'catid': 0,
  'color': (234, 119, 243),
  'hasInstances': True,
  'id': 87,
  'ignoreInEval': False,
  'name': 'scissors',
  'trainId': 255},
 {'category': 'indoor',
  'catid': 0,
  'color': (237, 122, 246),
  'hasInstances': True,
  'id': 88,
  'ignoreInEval': False,
  'name': 'teddy bear',
  'trainId': 255},
 {'category': 'indoor',
  'catid': 0,
  'color': (240, 125, 249),
  'hasInstances': True,
  'id': 89,
  'ignoreInEval': False,
  'name': 'hair drier',
  'trainId': 255},
 {'category': 'indoor',
  'catid': 0,
  'color': (243, 128, 252),
  'hasInstances': True,
  'id': 90,
  'ignoreInEval': False,
  'name': 'toothbrush',
  'trainId': 255}]



class Coco(BaseDataset):
    '''
    '''
    def __init__(self, dataroot, annpath, trans_func=None, mode='train'):
        super(Coco, self).__init__(
                dataroot, annpath, trans_func, mode)
        self.n_cats = 19
        self.lb_ignore = 255
        self.lb_map = np.arange(256).astype(np.uint8)
        for el in labels_info:
            self.lb_map[el['id']] = el['trainId']

        self.to_tensor = T.ToTensor(
            mean=(0.3257, 0.3690, 0.3223), # city, rgb
            std=(0.2112, 0.2148, 0.2115),
        )


def get_data_loader(datapth, annpath, ims_per_gpu, scales, cropsize, max_iter=None, mode='train', distributed=True):
    if mode == 'train':
        trans_func = TransformationTrain(scales, cropsize)
        batchsize = ims_per_gpu
        shuffle = True
        drop_last = True
    elif mode == 'val':
        trans_func = TransformationVal()
        batchsize = ims_per_gpu
        shuffle = False
        drop_last = False

    ds = Coco(datapth, annpath, trans_func=trans_func, mode=mode)

    if distributed:
        assert dist.is_available(), "dist should be initialzed"
        if mode == 'train':
            assert not max_iter is None
            n_train_imgs = ims_per_gpu * dist.get_world_size() * max_iter
            sampler = RepeatedDistSampler(ds, n_train_imgs, shuffle=shuffle)
        else:
            sampler = torch.utils.data.distributed.DistributedSampler(
                ds, shuffle=shuffle)
        batchsampler = torch.utils.data.sampler.BatchSampler(
            sampler, batchsize, drop_last=drop_last
        )
        dl = DataLoader(
            ds,
            batch_sampler=batchsampler,
            num_workers=4,
            pin_memory=True,
        )
    else:
        dl = DataLoader(
            ds,
            batch_size=batchsize,
            shuffle=shuffle,
            drop_last=drop_last,
            num_workers=4,
            pin_memory=True,
        )
    return dl



if __name__ == "__main__":
    from tqdm import tqdm
    from torch.utils.data import DataLoader
    ds = Coco('./data/', mode='val')
    dl = DataLoader(ds,
                    batch_size = 4,
                    shuffle = True,
                    num_workers = 4,
                    drop_last = True)
    for imgs, label in dl:
        print(len(imgs))
        for el in imgs:
            print(el.size())
        break
